/* RobotTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. RobotTokenManager.java */
package uniandes.lym.robot.control;
import uniandes.lym.robot.kernel.*;
import uniandes.lym.robot.view.Console;
import java.awt.Point;
import java.io.*;
import java.util.Vector;
import java.util.LinkedList;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.List;

/** Token Manager. */
@SuppressWarnings ("unused")
public class RobotTokenManager implements RobotConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x180000000L) != 0L)
            return 38;
         if ((active0 & 0x380L) != 0L)
         {
            jjmatchedKind = 46;
            return 29;
         }
         if ((active0 & 0x40040000000L) != 0L)
         {
            jjmatchedKind = 46;
            return 16;
         }
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 46;
            return 11;
         }
         if ((active0 & 0x810111df000L) != 0L)
         {
            jjmatchedKind = 46;
            return 27;
         }
         if ((active0 & 0x420040L) != 0L)
         {
            jjmatchedKind = 46;
            return 6;
         }
         if ((active0 & 0x1e000a00020L) != 0L)
         {
            jjmatchedKind = 46;
            return 1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 46;
            return 8;
         }
         if ((active0 & 0x20020000000L) != 0L)
         {
            jjmatchedKind = 46;
            return 23;
         }
         return -1;
      case 1:
         if ((active0 & 0xa00020L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 0;
         }
         if ((active0 & 0x80000000L) != 0L)
            return 51;
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 5;
         }
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 79;
         }
         if ((active0 & 0xa00L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 80;
         }
         if ((active0 & 0x9f0715fd000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 27;
         }
         if ((active0 & 0x2400L) != 0L)
            return 27;
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 15;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 22;
         }
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 31;
         }
         return -1;
      case 2:
         if ((active0 & 0x9e0715fd000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return 27;
         }
         if ((active0 & 0x40L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return 4;
         }
         if ((active0 & 0x40000000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return 14;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return 21;
         }
         if ((active0 & 0x80000000L) != 0L)
            return 50;
         if ((active0 & 0x1000000aa0L) != 0L)
            return 27;
         if ((active0 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 27;
               jjmatchedPos = 2;
            }
            return 27;
         }
         if ((active0 & 0x100L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return 30;
         }
         return -1;
      case 3:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 3;
            return 81;
         }
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 3;
            return 79;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 3;
            return 20;
         }
         if ((active0 & 0x9e030a21000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 3;
            return 27;
         }
         if ((active0 & 0x11dc100L) != 0L)
            return 27;
         if ((active0 & 0x40400000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return -1;
         }
         return -1;
      case 4:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 27;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 4;
            return 19;
         }
         if ((active0 & 0x9e030021000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 4;
            return 27;
         }
         if ((active0 & 0x40L) != 0L)
            return 27;
         if ((active0 & 0x40400000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 5:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 5;
            return 18;
         }
         if ((active0 & 0x58020000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 5;
            return 27;
         }
         if ((active0 & 0x86010021000L) != 0L)
            return 27;
         if ((active0 & 0x40400000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 6:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 6;
            return 81;
         }
         if ((active0 & 0x50000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 6;
            return 27;
         }
         if ((active0 & 0x8020000000L) != 0L)
            return 27;
         if ((active0 & 0x40400000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 7:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 7;
            return 27;
         }
         if ((active0 & 0x50000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 7;
            return 27;
         }
         if ((active0 & 0x40400000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0xa00000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x40000000000L) != 0L)
            return 27;
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 46;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x30000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 8;
            return 27;
         }
         return -1;
      case 9:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 9;
            return 27;
         }
         if ((active0 & 0x10000000000L) != 0L)
            return 27;
         return -1;
      case 10:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 10;
            return 27;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 47);
      case 41:
         return jjStopAtPos(0, 48);
      case 44:
         return jjStopAtPos(0, 49);
      case 58:
         return jjMoveStringLiteralDfa1_0(0x180000000L);
      case 59:
         return jjStopAtPos(0, 26);
      case 61:
         return jjStopAtPos(0, 25);
      case 63:
         return jjStopAtPos(0, 50);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x20020000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x40040000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1000001000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x10080000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x1e000a00020L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x380L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x420040L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x80000100000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x44000L);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x20050080000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x21000L);
      case 70:
      case 102:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(1, 13, 27);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000004000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000140L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x20008000L);
      case 79:
      case 111:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(1, 10, 27);
         return jjMoveStringLiteralDfa2_0(active0, 0xa10a20L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x1440080L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x1e000000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x80080000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x8010080100L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x20001000000L);
      case 77:
      case 109:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 36, 27);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x40400000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x20010000L);
      case 80:
      case 112:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 27);
         else if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(2, 11, 27);
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 84:
      case 116:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 27);
         break;
      case 86:
      case 118:
         if ((active0 & 0x20L) != 0L)
         {
            jjmatchedKind = 5;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0xa00000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa4_0(active0, 0x40400000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x80020000000L);
      case 69:
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 15, 27);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 27);
         return jjMoveStringLiteralDfa4_0(active0, 0xa20000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000040L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x110000000L);
      case 75:
      case 107:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 27);
         break;
      case 76:
      case 108:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 27);
         return jjMoveStringLiteralDfa4_0(active0, 0x20080000000L);
      case 78:
      case 110:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(3, 14, 27);
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 27);
         break;
      case 80:
      case 112:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 27);
         else if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 27);
         return jjMoveStringLiteralDfa4_0(active0, 0x46000000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa5_0(active0, 0xa00000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x21000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x10080000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x26000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x140000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L);
      case 84:
      case 116:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 27);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 71:
      case 103:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(5, 28, 27);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x20080000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000L);
      case 82:
      case 114:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 27);
         break;
      case 83:
      case 115:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(5, 32);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 37, 27);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 27);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 43, 27);
         break;
      case 84:
      case 116:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 17, 27);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 68:
      case 100:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(6, 29, 27);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x10080000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000L);
      case 83:
      case 115:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 39, 27);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 63:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(7, 30);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L);
      case 82:
      case 114:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(7, 21);
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000000L);
      case 83:
      case 115:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(7, 22);
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(8, 23);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 42, 27);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000L);
      case 83:
      case 115:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(8, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000L);
      case 83:
      case 115:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 40, 27);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 82:
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 41, 27);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 79;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 31:
               case 27:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 44)
                        kind = 44;
                     { jjCheckNAdd(25); }
                  }
                  else if (curChar == 58)
                     { jjAddStates(0, 10); }
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  { jjCheckNAdd(25); }
                  break;
               case 34:
                  if (curChar == 58)
                     { jjAddStates(0, 10); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 31:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 18:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x400000004000L & l) != 0L)
                     { jjCheckNAdd(13); }
                  break;
               case 16:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 22:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 20:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 38:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  else if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  else if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  else if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  else if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  else if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  else if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  else if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  else if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 47;
                  else if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  else if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 81:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x8000000080000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                  }
                  break;
               case 11:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x800000008000L & l) != 0L)
                     { jjCheckNAdd(10); }
                  break;
               case 29:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x800000008000L & l) != 0L)
                     { jjCheckNAdd(10); }
                  else if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  else if ((0x20000000200000L & l) != 0L)
                     { jjCheckNAdd(3); }
                  break;
               case 5:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x40000000400000L & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                  }
                  break;
               case 30:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x80000000800L & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                  }
                  break;
               case 19:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 23:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 21:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 15:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x1000000010000L & l) != 0L)
                     { jjCheckNAdd(13); }
                  break;
               case 80:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x1000000010000L & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                  }
                  break;
               case 8:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x800000008000L & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                  }
                  break;
               case 6:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 4:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x10000000100L & l) != 0L)
                     { jjCheckNAdd(3); }
                  break;
               case 79:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x10000000100000L & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                  }
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 2:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     { jjCheckNAdd(27); }
                  }
                  if ((0x1000000010000L & l) != 0L)
                     { jjAddStates(11, 13); }
                  else if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  else if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  else if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((0x10000000100000L & l) != 0L && kind > 27)
                     kind = 27;
                  break;
               case 7:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if ((0x1000000010000L & l) != 0L && kind > 27)
                     kind = 27;
                  break;
               case 12:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if ((0x8000000080000L & l) != 0L && kind > 33)
                     kind = 33;
                  break;
               case 17:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 24:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 26:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 27:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(27); }
                  break;
               case 28:
                  if ((0x1000000010000L & l) != 0L)
                     { jjAddStates(11, 13); }
                  break;
               case 32:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if ((0x800000008000L & l) != 0L)
                     { jjCheckNAdd(10); }
                  break;
               case 35:
                  if ((0x10000000100000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 36:
                  if ((0x4000000040L & l) != 0L)
                     { jjCheckNAdd(35); }
                  break;
               case 37:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 39:
                  if ((0x10000000100L & l) != 0L)
                     { jjCheckNAdd(35); }
                  break;
               case 40:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if ((0x1000000010L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 44:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if ((0x80000000800L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 50:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if ((0x400000004000L & l) != 0L)
                     { jjCheckNAdd(35); }
                  break;
               case 54:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if ((0x1000000010000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 58:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if ((0x400000004000L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 60:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x10000000100L & l) != 0L && kind > 35)
                     kind = 35;
                  break;
               case 64:
               case 68:
                  if ((0x10000000100000L & l) != 0L)
                     { jjCheckNAdd(63); }
                  break;
               case 65:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 69:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if ((0x10000000100000L & l) != 0L && kind > 35)
                     kind = 35;
                  break;
               case 73:
               case 76:
                  if ((0x8000000080000L & l) != 0L)
                     { jjCheckNAdd(72); }
                  break;
               case 74:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 77:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 79 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, "\75", 
"\73", null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, "\50", "\51", "\54", "\77", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   38, 42, 48, 52, 56, 58, 62, 67, 71, 75, 78, 29, 32, 33, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError();
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

    /** Constructor. */
    public RobotTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public RobotTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 79; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, 
};
static final long[] jjtoToken = {
   0x7dfffffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[79];
    private final int[] jjstateSet = new int[2 * 79];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
