/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int DEFVAR = 12;
  /** RegularExpression Id. */
  int DEFUN = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int LOOP = 17;
  /** RegularExpression Id. */
  int REPEAT = 18;
  /** RegularExpression Id. */
  int TURN = 19;
  /** RegularExpression Id. */
  int FACE = 20;
  /** RegularExpression Id. */
  int CMD_SKIP = 21;
  /** RegularExpression Id. */
  int MOVEDIR = 22;
  /** RegularExpression Id. */
  int RUNDIRS = 23;
  /** RegularExpression Id. */
  int MOVEFACE = 24;
  /** RegularExpression Id. */
  int NULL = 25;
  /** RegularExpression Id. */
  int ASSIGN = 26;
  /** RegularExpression Id. */
  int SEMICOLON = 27;
  /** RegularExpression Id. */
  int NAME = 28;
  /** RegularExpression Id. */
  int FACING = 29;
  /** RegularExpression Id. */
  int BLOCKED = 30;
  /** RegularExpression Id. */
  int CANPUT = 31;
  /** RegularExpression Id. */
  int CANPICK = 32;
  /** RegularExpression Id. */
  int CANMOVE = 33;
  /** RegularExpression Id. */
  int ISZERO = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int BALLOONS = 36;
  /** RegularExpression Id. */
  int CHIPS = 37;
  /** RegularExpression Id. */
  int OBJECTYPE = 38;
  /** RegularExpression Id. */
  int DIRECTION = 39;
  /** RegularExpression Id. */
  int ORIENTATION = 40;
  /** RegularExpression Id. */
  int DIM = 41;
  /** RegularExpression Id. */
  int MYXPOS = 42;
  /** RegularExpression Id. */
  int MYYPOS = 43;
  /** RegularExpression Id. */
  int MYCHIPS = 44;
  /** RegularExpression Id. */
  int MYBALLOONS = 45;
  /** RegularExpression Id. */
  int BALLOONSHERE = 46;
  /** RegularExpression Id. */
  int CHIPSHERE = 47;
  /** RegularExpression Id. */
  int SPACES = 48;
  /** RegularExpression Id. */
  int NUM = 49;
  /** RegularExpression Id. */
  int DIGIT = 50;
  /** RegularExpression Id. */
  int IDENTIFIER = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"defvar\"",
    "\"defun\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"loop\"",
    "\"repeat\"",
    "\"turn\"",
    "\"face\"",
    "\"skip\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move-face\"",
    "\"null\"",
    "\"=\"",
    "\";\"",
    "<NAME>",
    "\"facing\"",
    "\"blocked?\"",
    "\"can-put?\"",
    "\"can-pick?\"",
    "\"can-move?\"",
    "\"isZero?\"",
    "\"not\"",
    "\":balloons\"",
    "\":chips\"",
    "<OBJECTYPE>",
    "<DIRECTION>",
    "<ORIENTATION>",
    "\"dim\"",
    "\"myXpos\"",
    "\"myYpos\"",
    "\"myChips\"",
    "\"myBalloons\"",
    "\"balloonsHere\"",
    "\"chipsHere\"",
    "\"spaces\"",
    "<NUM>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"?\"",
  };

}
